In [34]:
import requests
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

## DJI

In [45]:
pageLink = 'https://finance.yahoo.com/quote/^DJI/history?period1=1509422400&period2=1540958400&interval=1d&filter=history&frequency=1d'
pageResponse = requests.get(pageLink)
pageContent = BeautifulSoup(pageResponse.content, 'html.parser')
tableContent = []
tablesHead = pageContent.find_all('thead')[0]
tablesBody = pageContent.find_all('tbody')[0]

In [46]:
# Table headings
headingTags = tablesHead.select("span")
headings = [i.get_text() for i in headingTags]
# Table content
bodyTags = tablesBody.select("span")
bodies = [i.get_text() for i in bodyTags]
bodies = np.reshape(bodies,(int((len(bodies) / 7)),7))
bodiesDF = pd.DataFrame(bodies)

In [47]:
DJI = pd.DataFrame({'Date': bodiesDF[0], 'Open': bodiesDF[1], 
                    'High':bodiesDF[2], 'Low':bodiesDF[3], 
                    'Close':bodiesDF[4], 'AdjClose':bodiesDF[5], 
                    'Volume':bodiesDF[6]})

In [48]:
DJI

,Date,Open,High,Low,Close,AdjClose,Volume
0,"Oct 30, 2018","24,482.04","24,906.68","24,415.69","24,874.64","24,874.64","470,050,000"
1,"Oct 29, 2018","24,818.98","25,040.58","24,122.23","24,442.92","24,442.92","443,850,000"
2,"Oct 26, 2018","24,770.25","24,916.16","24,445.19","24,688.31","24,688.31","505,310,000"
3,"Oct 25, 2018","24,736.54","25,104.29","24,645.56","24,984.55","24,984.55","439,670,000"
4,"Oct 24, 2018","25,172.88","25,306.23","24,533.19","24,583.42","24,583.42","496,400,000"
5,"Oct 23, 2018","25,038.46","25,307.70","24,768.79","25,191.43","25,191.43","436,430,000"
6,"Oct 22, 2018","25,492.14","25,561.34","25,236.05","25,317.41","25,317.41","314,940,000"
7,"Oct 19, 2018","25,421.09","25,608.71","25,350.02","25,444.34","25,444.34","350,810,000"
8,"Oct 18, 2018","25,645.56","25,691.46","25,236.01","25,379.45","25,379.45","328,020,000"
9,"Oct 17, 2018","25,705.87","25,810.09","25,479.16","25,706.68","25,706.68","298,210,000"
10,"Oct 16, 2018","25,351.53","25,817.68","25,351.53","25,798.42","25,798.42","305,800,000"
11,"Oct 15, 2018","25,332.46","25,482.42","25,243.88","25,250.55","25,250.55","287,320,000"
12,"Oct 12, 2018","25,407.63","25,467.55","25,000.83","25,339.99","25,339.99","397,510,000"
13,"Oct 11, 2018","25,518.39","25,683.64","24,899.77","25,052.83","25,052.83","522,880,000"
14,"Oct 10, 2018","26,441.73","26,487.87","25,567.10","25,598.74","25,598.74","438,200,000"
15,"Oct 09, 2018","26,469.19","26,539.94","26,324.16","26,430.57","26,430.57","282,560,000"
16,"Oct 08, 2018","26,399.45","26,529.35","26,223.09","26,486.78","26,486.78","273,020,000"
17,"Oct 05, 2018","26,632.77","26,676.16","26,301.81","26,447.05","26,447.05","267,100,000"
18,"Oct 04, 2018","26,784.08","26,793.82","26,471.61","26,627.48","26,627.48","289,600,000"
19,"Oct 03, 2018","26,833.47","26,951.81","26,789.08","26,828.39","26,828.39","280,130,000"
20,"Oct 02, 2018","26,648.91","26,824.78","26,627.66","26,773.94","26,773.94","258,290,000"
21,"Oct 01, 2018","26,598.36","26,737.98","26,596.05","26,651.21","26,651.21","238,320,000"
22,"Sep 28, 2018","26,407.66","26,515.76","26,383.57","26,458.31","26,458.31","264,030,000"
23,"Sep 27, 2018","26,418.27","26,557.01","26,379.95","26,439.93","26,439.93","226,350,000"
24,"Sep 26, 2018","26,536.86","26,606.09","26,349.34","26,385.28","26,385.28","262,620,000"
25,"Sep 25, 2018","26,601.58","26,634.85","26,475.58","26,492.21","26,492.21","234,110,000"
26,"Sep 24, 2018","26,705.25","26,709.94","26,548.68","26,562.05","26,562.05","254,850,000"
27,"Sep 21, 2018","26,726.25","26,769.16","26,680.37","26,743.50","26,743.50","657,620,000"
28,"Sep 20, 2018","26,519.39","26,697.49","26,519.39","26,656.98","26,656.98","260,480,000"
29,"Sep 19, 2018","26,287.84","26,464.41","26,280.76","26,405.76","26,405.76","251,330,000"
...,...,...,...,...,...,...,...
70,"Jul 23, 2018","25,036.90","25,081.45","24,983.33","25,044.29","25,044.29","228,820,000"
71,"Jul 20, 2018","25,041.14","25,124.10","24,986.35","25,058.12","25,058.12","274,080,000"
72,"Jul 19, 2018","25,139.15","25,154.17","25,052.62","25,064.50","25,064.50","285,760,000"
73,"Jul 18, 2018","25,133.79","25,215.32","25,101.12","25,199.29","25,199.29","252,870,000"
74,"Jul 17, 2018","25,033.92","25,155.39","24,989.61","25,119.89","25,119.89","250,450,000"
75,"Jul 16, 2018","25,025.58","25,072.41","24,979.64","25,064.36","25,064.36","231,270,000"
76,"Jul 13, 2018","24,926.07","25,043.21","24,890.06","25,019.41","25,019.41","255,520,000"
77,"Jul 12, 2018","24,802.90","24,939.97","24,802.90","24,924.89","24,924.89","233,150,000"
78,"Jul 11, 2018","24,789.48","24,815.16","24,663.82","24,700.45","24,700.45","237,370,000"
79,"Jul 10, 2018","24,806.97","24,945.38","24,806.97","24,919.66","24,919.66","235,040,000"
80,"Jul 09, 2018","24,519.20","24,796.52","24,518.43","24,776.59","24,776.59","240,580,000"
81,"Jul 06, 2018","24,352.47","24,520.29","24,281.47","24,456.48","24,456.48","219,450,000"
82,"Jul 05, 2018","24,285.82","24,372.80","24,177.44","24,356.74","24,356.74","237,670,000"
83,"Jul 03, 2018","24,359.39","24,444.88","24,150.85","24,174.82","24,174.82","160,960,000"
84,"Jul 02, 2018","24,161.53","24,319.42","24,077.56","24,307.18","24,307.18","244,110,000"
85,"Jun 29, 2018","24,323.93","24,509.52","24,269.71","24,271.41","24,271.41","329,070,000"
86,"Jun 28, 2018","24,064.19","24,308.16","23,997.21","24,216.05","24,216.05","305,020,000"
87,"Jun 27, 2018","24,303.11","24,569.02","24,115.82","24,117.59","24,117.59","313,790,000"
88,"Jun 26, 2018","24,281.89","24,384.21","24,241.22","24,283.11","24,283.11","301,130,000"
89,"Jun 25, 2018","24,463.73","24,463.73","24,084.39","24,252.80","24,252.80","439,130,000"
90,"Jun 22, 2018","24,526.97","24,663.18","24,526.97","24,580.89","24,580.89","473,970,000"
91,"Jun 21, 2018","24,639.21","24,639.21","24,406.63","24,461.70","24,461.70","349,570,000"
92,"Jun 20, 2018","24,771.17","24,804.76","24,628.39","24,657.80","24,657.80","359,520,000"
93,"Jun 19, 2018","24,763.59","24,763.59","24,567.75","24,700.21","24,700.21","376,380,000"
94,"Jun 18, 2018","24,944.28","25,003.10","24,825.77","24,987.47","24,987.47","337,070,000"
95,"Jun 15, 2018","25,116.71","25,130.82","24,894.38","25,090.48","25,090.48","659,370,000"
96,"Jun 14, 2018","25,254.65","25,332.50","25,138.60","25,175.31","25,175.31","341,170,000"
97,"Jun 13, 2018","25,328.65","25,362.07","25,191.42","25,201.20","25,201.20","329,700,000"
98,"Jun 12, 2018","25,346.82","25,364.37","25,247.04","25,320.73","25,320.73","265,750,000"
99,"Jun 11, 2018","25,336.67","25,402.83","25,290.20","25,322.31","25,322.31","276,740,000"